### ISSUE TITLE
Amoeba 3.0 are not use 8 Threads in ChessGUI

### ISSUE THREAD

**Issue by gpaunica** [abulmo/amoeba#15]
Hello Mr/Mrs,
I installed Amoeba 3.0 in ChessGUI chess GUI (http://www.chess.hylogic.de/), but Amoeba uses 1 Thread only.
Thanks.

**Comment by abulmo** [comment]
Hello,
Unfortunately, I am unable to understand how ChessGUI works. I am not clever enough to install, configure and run a single engine on it (I tried with amoeba 3.0 and spike 1.4 without success). If you succeed at installing amoeba 3.0 and ran it on a single thread you are luckier than me. 
To run on 8 threads, amoeba needs to receive the following command:
`setoption name Threads value 8`
Due to my limited skill with ChessGUI, I have no idea if there is something wrong in Amoeba or in ChessGUI. Have you tried to contact the ChessGUI's author, maybe his GUI does not support multithreaded engine ?

**Comment by abulmo** [comment]
It seems to be a bug in chessgui. A workaround is described here:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=1486&start=50#p114105
Basically you need to edit the config file manually and set threads to 8, 4 or whatever you like.
